// projectDesign.js - Design System Tokens
window.projectDesign = {
  "colorMode": "LIGHT",
  "font": "PUBLIC_SANS",
  "roundness": "ROUND_EIGHT",
  "customColor": "#0A2540",
  "headlineFont": "PUBLIC_SANS",
  "bodyFont": "PUBLIC_SANS",
  "labelFont": "PUBLIC_SANS",
  "namedColors": {
    "background": "#fcf9f8",
    "error": "#ba1a1a",
    "error_container": "#ffdad6",
    "inverse_on_surface": "#f3f0ef",
    "inverse_primary": "#b0c8eb",
    "inverse_surface": "#313030",
    "on_background": "#1c1b1b",
    "on_error": "#ffffff",
    "on_error_container": "#93000a",
    "on_primary": "#ffffff",
    "on_primary_container": "#768dad",
    "on_primary_fixed": "#001c37",
    "on_primary_fixed_variant": "#314865",
    "on_secondary": "#ffffff",
    "on_secondary_container": "#fffbff",
    "on_secondary_fixed": "#410007",
    "on_secondary_fixed_variant": "#92001c",
    "on_surface": "#1c1b1b",
    "on_surface_variant": "#43474d",
    "on_tertiary": "#ffffff",
    "on_tertiary_container": "#898b8c",
    "on_tertiary_fixed": "#191c1d",
    "on_tertiary_fixed_variant": "#454748",
    "outline": "#74777e",
    "outline_variant": "#c4c6ce",
    "primary": "#000f22",
    "primary_container": "#0a2540",
    "primary_fixed": "#d2e4ff",
    "primary_fixed_dim": "#b0c8eb",
    "secondary": "#b7102a",
    "secondary_container": "#db313f",
    "secondary_fixed": "#ffdad8",
    "secondary_fixed_dim": "#ffb3b1",
    "surface": "#fcf9f8",
    "surface_bright": "#fcf9f8",
    "surface_container": "#f0eded",
    "surface_container_high": "#eae7e7",
    "surface_container_highest": "#e5e2e1",
    "surface_container_low": "#f6f3f2",
    "surface_container_lowest": "#ffffff",
    "surface_dim": "#dcd9d9",
    "surface_tint": "#49607e",
    "surface_variant": "#e5e2e1",
    "tertiary": "#0c0f10",
    "tertiary_container": "#212425",
    "tertiary_fixed": "#e1e3e4",
    "tertiary_fixed_dim": "#c5c7c8"
  },
  "typography": {
    "body-lg": {"fontFamily": "Public Sans", "fontSize": "18px", "fontWeight": "400", "lineHeight": "1.7"},
    "body-md": {"fontFamily": "Public Sans", "fontSize": "16px", "fontWeight": "400", "lineHeight": "1.6"},
    "headline-lg": {"fontFamily": "Public Sans", "fontSize": "32px", "fontWeight": "700", "lineHeight": "1.25", "letterSpacing": "-0.01em"},
    "headline-md": {"fontFamily": "Public Sans", "fontSize": "24px", "fontWeight": "600", "lineHeight": "1.3"},
    "headline-xl": {"fontFamily": "Public Sans", "fontSize": "48px", "fontWeight": "700", "lineHeight": "1.2", "letterSpacing": "-0.02em"},
    "label-bold": {"fontFamily": "Public Sans", "fontSize": "14px", "fontWeight": "700", "lineHeight": "1.4", "letterSpacing": "0.05em"},
    "label-sm": {"fontFamily": "Public Sans", "fontSize": "12px", "fontWeight": "500", "lineHeight": "1.4"}
  },
  "spacing": {
    "base": "8px",
    "gutter": "24px",
    "lg": "48px",
    "margin": "32px",
    "md": "24px",
    "sm": "12px",
    "xl": "80px",
    "xs": "4px"
  }
};
